[package]
name = "code-racer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
color-backtrace = "0.7.2"
color-eyre = "0.6.5"
tempfile = "3.23.0"
